development:
  adapter: mysql2
  database: git_reviewer_development
  username: root
  password:

test:
  adapter: mysql2
  database: git_reviewer_test
  username: root
  password:

production:
  adapter: mysql2
  database: git_reviewer_production
  host: localhost
  username: root
  password: 'casino!@#'
